# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20160905_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowing_times',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='borrowing times'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Add the classification of the books ', null=True, related_name='user_set', to='firstapp.BookCategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='note',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='bookborrowinfo',
            name='standard_return_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 9, 11, 25, 44, 813000)),
        ),
    ]
