# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 11:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20160906_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Add the classification of the books ', related_name='user_set', to='firstapp.BookCategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='bookborrowinfo',
            name='standard_return_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 9, 11, 26, 26, 221000)),
        ),
    ]
