# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 17:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20160906_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemstatus',
            options={'default_permissions': ('view', 'change', 'add', 'delete'), 'ordering': ('-id',), 'verbose_name': 'system status', 'verbose_name_plural': 'system status'},
        ),
        migrations.AlterField(
            model_name='book',
            name='number',
            field=models.CharField(help_text='Serial number must be unique', max_length=500, unique=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='bookborrowinfo',
            name='standard_return_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 9, 17, 32, 21, 913000)),
        ),
    ]
