# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20160908_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'student',
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.RemoveField(
            model_name='bookborrowinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='bookborrowinfo',
            name='standard_return_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 15, 15, 13, 23, 440000)),
        ),
        migrations.AddField(
            model_name='bookborrowinfo',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Student'),
            preserve_default=False,
        ),
    ]
