# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_auto_20160912_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookborrowinfo',
            name='standard_return_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 15, 15, 13, 32, 985000)),
        ),
    ]
